base_link2camera:
  x: 1.0
  y: 0.0
  z: 2.0
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
base_link2velodyne:
  x: 0.0
  y: 0.0
  z: 2.0
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
base_link2imu:
  x: 1.0
  y: 0.0
  z: 2.1
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
